--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PEMapModder/HereAuth
projects:
  HereAuth:
    path: ""
    model: nowhere
    icon: hereauth.png
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0
...
